name:                html-to-sql
version:             0.1.0.0
github:              "githubuser/html-to-sql"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/html-to-sql#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- text
- mysql-simple == 0.4.5
- ssh-tunnel
- unix
- http-client
- attoparsec
- load-env
- system-filepath
- scientific

library:
  source-dirs: src

executables:
  html-to-sql-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-orphans
    dependencies:
    - html-to-sql

tests:
  html-to-sql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - html-to-sql
